group=dev.libalpm64.speleothem
mcVersion=26.2
apiVersion=26.2
channel=BETA
clipVersion=3.0.18
weightVersion=2.0.15
# true for release, false for skip release, pre for pre-release
release=true
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

foliaRef=57f643f10e0a9d01024773232d38ae666067d593

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
